### ISSUE TITLE
Notch overlapping with menu header in freecodecamp flutter app

### ISSUE THREAD

**Issue by ujwal49** [freeCodeCamp/mobile#107]
**Describe the bug**
My phones notch and the freecodecamp header in the flutter app are overlapping.

**To Reproduce**
1. Go to freecodecamp flutter app(Android)
2. Click on the navigation menu on the top left of the screen
3. Click on learn
4. You can see the bug popping on the notch 

**Expected behavior**
Maybe It's not using enough padding to show it below my phone's notch leading fcc header and my notch to overlap.

*Screenshots**
![notch-bug](https://user-images.githubusercontent.com/65085816/145747269-23960d01-a434-4064-bb45-99d53a5c9ab9.jpg)

**Sma

rtphone (please complete the following information):**
 - Device: Oneplus7
 - OS: oxygen OS 11.0.3.1
 - Android: Freecodecamp flutter app

**Comment by Rishab-ms** [comment]
I will work on this 👍🏻

**Comment by Sembauke** [comment]
Hi @ujwal49 an update should already be available for this bug 😁

**Comment by ujwal49** [comment]
Yep the update fixed it
Thank you
