### ISSUE TITLE
type 'String' is not a subtype of 'Widget?'

### ISSUE THREAD

**Issue by arice77** [freeCodeCamp/mobile#1094]
![Screenshot_2023-08-21-15-25-35-90_5f759941e40c3b4ea769d2ffa19638e0](https://github.com/freeCodeCamp/mobile/assets/92450890/c84135d0-da72-47d5-810c-d589dd096645)
When navigated to Podcast Page ,the screen turns red with a text that says: type 'String' is not a subtype of 'Widget?'

**To Reproduce**
1. Open the App Drawer
2. Click on "Podcasts"

**Expected behavior**
Podcast Page with title as "PODCASTS"

**Smartphone (please complete the following information):**
 - Device: Realme Narzo 30 A
 - OS: Android 11

**Comment by SadanandMiskin** [comment]
Assign me
