### ISSUE TITLE
Auth & User Settings

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/mobile#11]
As a user I want to be able to:

- [x] Login using freeCodeCamp via OAuth 2.0
- [x] View my profile & progress on the web app.
- [ ] Update my profile and user settings.
- [ ] Delete my account.

**Comment by nikunjdk** [comment]
Is there any api for login and getting user profile by freeCodeCamp?

**Comment by Sembauke** [comment]
Login screen:
https://www.figma.com/file/c70xPjT9ZsDVaUZAV0NmRv/Untitled?node-id=0%3A1
![image](https://user-images.githubusercontent.com/46919888/127320486-8941e1fe-23cf-4493-b2a7-b6f28b5ea617.png)

**Comment by Nirajn2311** [comment]
Instead of "Go Back", we could add a back button(arrow) at the top left. I feel thats more intuitive to the users.

**Comment by Michelphoenix98** [comment]
Is this issue still open?

**Comment by Nirajn2311** [comment]
Yes and I'm currently working on it in PR - #310
