### ISSUE TITLE
Code Radio does not load in the app.

### ISSUE THREAD

**Issue by TomCarroll09** [freeCodeCamp/mobile#1103]
**Describe the bug**
When i go to the code radio section of the app the code radio does not load or play. all i see is the loading symbol. it does not load at all no matter how long i wait.

**To Reproduce**
1. Go to Code radio
2. Code radio does not load.

**Expected behavior**
I expected the code radio to load.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: Android13 with OneUI core 5.1
 - Browser Firefox
 - Version 4.1.1

**Additional context**
The code radio works fine in the browsers i use (Firefox and Duckduckgo browser) but in the app it does not.

**Comment by Nirajn2311** [comment]
Thanks for the report @TomCarroll09 . We've found the bug and fixed it. You can expect coderadio to be working from the next update.
