### ISSUE TITLE
Code Radio stops playing when i exit the app.

### ISSUE THREAD

**Issue by TomCarroll09** [freeCodeCamp/mobile#1112]
**Describe the bug**
Whenever i am listening to the code radio exiting the app, my screen turning off or my screen timing out will cause the music to stop playing. The notification will show that the music is still playing however.

**To Reproduce**
1. Go to code radio
2. Click on play
3. exit the app
4. music stops playing

**Expected behavior**
I expected the music to keep playing.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: Android 13
 - Browser duckduckgo browser and firefox
 - Version 4.1.2

**Comment by opxdelwin** [comment]
Hi @TomCarroll09,
I've tested it with few of my phones (1+ Nord, Samsung S8) and it works perfectly fine.... Could you try cloning the repo and running a debug version on your phone (using cable) and getting us any logs?

**Comment by TomCarroll09** [comment]
The app updated a few days ago and the problem is now fixed.

**Comment by opxdelwin** [comment]
@TomCarroll09 That's nice, feel free to close this issue :)
