### ISSUE TITLE
FreeCodeCamp mobile app bug when trying out python courses such as maching learning

### ISSUE THREAD

**Issue by FiredMosquito831** [freeCodeCamp/mobile#1151]
**Describe the bug**
When i go into the in app course for machine learning with python when i press on a lesson i just see a grey screen and nothing happens

**To Reproduce**
1. Go to 'Machine learning with python or any other python course'
2. Click on 'any lesson(for example introduction: Machnie learning fundamentals'
3. See error

**Expected behavior**
See the course, either video or input window

**Screenshots**
A video i also sent in the discord server
https://cdn.discordapp.com/attachments/693145545878929499/1170428981909135450/Screen_Recording_20231104_202628.mp4?ex=655901ee&is=65468cee&hm=e8680ca1c74282bac10ac6a24726c9a3070ef3794aa6723b4656ba2cf7adb7b3&

**Smartphone (please complete the following information):**
 - Device: samsung z fold 4
 - OS: android 13 oneui 5.1
 - Browser FreeCodeCamp app android
 - Version latest version

**Additional context**

**Comment by harelbt** [comment]
Also on ios 17

**Comment by Nirajn2311** [comment]
Hi @harelbt , we've fixed the bug and the next update will allow you to open the python challenges.
