### ISSUE TITLE
OS Back Button Exits Instead of Returning

### ISSUE THREAD

**Issue by is-lucky** [freeCodeCamp/mobile#1163]
**Describe the bug**
After using the drop-down hamburger menu to access "Tutorials", "Podcasts", or "Code Radio" if the mobile’s built-in back button is pressed it exits the application rather than returning to the home page ("Learn").

**To Reproduce**
1. Go to the three-line 'hamburger' menu in the upper left corner of the app
2. Click on any of TUTORIALS, PODCASTS, or CODE RADIO
3. Click on the mobile OS's built-in back button option

**Expected behavior**
Using the back button from any of the above pages should take the user to the page they were previously on (LEARN).

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android version 10
 - freeCodeCamp mobile app
 - Version 4.1.7

**Comment by Sembauke** [comment]
Hey @is-lucky,

Thank you for taking the time to create an issue for this. Although this behaviour is not best practice, this is the desired behaviour. 

This decision was made to save memory on the phone and ensure that Learn is running soothly. 

Thank you for your understanding and happy coding!
