### ISSUE TITLE
Submissions won't go through anymore

### ISSUE THREAD

**Issue by Fran5ois** [freeCodeCamp/mobile#1165]
Hello here!

 The submission has stopped working few weeks ago in the android app on my smartphone. 
When I submit any code of any step, the blue check mark turns into a the rotating animation for a fraction of a second and goes back to the blue check mark, with no prompt.
Since then I have been doing my projects on the website with no issue, but the app is far more convenient so I would love a way to get it back.

**To Reproduce**
1. Go to 'learn'
2. Choose any step, for example " Learn HTML forms..." step 1.
3. Enter the correct code, for example <!DOCTYPE html>
4. Tap on blue check mark.
5. The icon turns and goes back to check mark and nothing happens.

**Expected behavior**
Check mark turns green and permits access to next step. Or hint prompt in case of wrong code.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy note 10plus
 - OS: android 12, one ui 4.1
 - Browser samsung internet

**Additional context**
I tried this with no effect:

updated the app
restarted the app
restarted my phone (galaxy note 10plus)
cleared cache
cleared data
cleared chache from within the app
uninstalled and installed the app again... several time each :]

Would it be possible that commucation from app to server fails?

Would anyone have a solution? The browser version on mobile is quite unusable, and the app rocks... I would love it back

**Comment by bkataru** [comment]
Same issue here. The submit button loads but then stops abruptly. Can this be fixed, please? The mobile app is excellent apart from this annoying bug.

**Comment by Sembauke** [comment]
Hey @Fran5ois,

Thank you for telling us this. I will look in to it immediately.

**Comment by Fran5ois** [comment]
The issue is still the same here... should I wait for an update on google play? Or is there anything else I should do?

**Comment by Sembauke** [comment]
@bkataru, @Fran5ois  the issue should be fixed. Don't forget to update to v4.1.8

**Comment by Fran5ois** [comment]
Yes I could see the update now, and indeed the issue is fixed!!! Many thanks and a happy and enriching new year to you all!

**Comment by Sembauke** [comment]
Thank you for letting us know!
