### ISSUE TITLE
In the Learn section clicking an unsupported cert/path permanent pop-up

### ISSUE THREAD

**Issue by Wangstaboi** [freeCodeCamp/mobile#1167]
**Describe the bug**
There is a pop up notification upon attempting to access a certificate that is currently unsupported on the mobile app. The pop up does not disappear, and persists indefinitely unless the app is closed. Because of this the hamburger/side menu is inaccessible without restarting the app.

**To Reproduce**
1. Go to LEARN
2. Click on any greyed out certificate.
3. See error

**Expected behavior**
The pop up notification displays for a few seconds, and then disappears shortly.

**Screenshots**
![Screenshot_20240103-213143_freeCodeCamp](https://github.com/freeCodeCamp/mobile/assets/92279949/73fae2ca-0b7b-4b1e-a9d7-14d4a82c9922)

**Smartphone (please complete the following information):**
 - Device: Motorola Edge+ 2023
 - OS: Android 13
 - Browser: Firefox
 - Version: 121

**Comment by Kavan2003** [comment]
I want to solve ths and contribute can you assign me issue

**Comment by Nirajn2311** [comment]
You can dismiss it by swiping it up. But we'll make it so that is disappears after a couple of seconds

**Comment by Wangstaboi** [comment]
> You can dismiss it by swiping it up. But we'll change it so that is disappears after a couple of seconds

I had no idea. I thought it was supposed to be a toast notification that would disappear.
