### ISSUE TITLE
Podcast episode preview content is same for all episodes

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/mobile#1175]
**Describe the bug**
In the episode list view of a podcast, each episode has the same preview content which is the podcast description.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Podcasts
2. Click on any podcast
3. See the preview content under each episode is the same as the podcast description.

**Expected behaviour**
The preview content for episode should be taken from the RSS feed if present.

**Comment by Sanket6652** [comment]
I want to solve this  issue and contribute can you assign me
