### ISSUE TITLE
Modify feedback for incorrect “ on app

### ISSUE THREAD

**Issue by PandoraGoat** [freeCodeCamp/mobile#1222]
**Is your feature request related to a problem? Please describe.**
I found out recently when trying to do a course on the app after having done the previous course on pc. That the default “ on ios at least, doesn't work in html code. It will simply say you are missing a whole attribute and not that your quote marks should be " instead. I had everything correct except the pesky “.

**Describe the solution you'd like**
Id suggest changing or adding feedback in the app, for the user to check if the correct " is used.

**Describe alternatives you've considered**
Its also possible that the app could simply auto add "" when pressing “ but i imagine this is more complex than simply adding text feedback.

**Additional context**
Here is the forum post i made to clarify what was going on https://forum.freecodecamp.org/t/learn-basic-css-by-building-a-cafe-menu-step-1/683137?u=pandoragoat

Here is a screenshot of what the current feedback looks like.
![IMG_3959](https://github.com/freeCodeCamp/mobile/assets/165647812/6d72b054-919a-4371-97c2-40afb4d7af95)

**Comment by Nirajn2311** [comment]
Hi, this is strange as we have disabled smart punctuations and when you click the double quotes it gets converted to the non-smart version. Did you copy paste the code from somewhere or do you use a different keyboard than the default Apple one?
