### ISSUE TITLE
Add content below the menu

### ISSUE THREAD

**Issue by diamant3** [freeCodeCamp/mobile#125]
Like authors, copyright or social links for the app just to occupy the space.

**Comment by Chinmay-KB** [comment]
@Sembauke @diamant3 can I work on this issue

**Comment by Sembauke** [comment]
Yes go for it, we can pair on this pull request: https://github.com/freeCodeCamp/mobile/pull/158

**Comment by Sembauke** [comment]
Hey @Chinmay-KB,

I am waiting on #158 to get merged.

After this, there is an better opportunity to start this.

**Comment by Chinmay-KB** [comment]
@Sembauke Okay!

**Comment by Chinmay-KB** [comment]
@Sembauke #158 is merged. What can I work on now

**Comment by Sembauke** [comment]
Yep!

**Comment by Nirajn2311** [comment]
@Chinmay-KB Hi, you can start working on this.

**Comment by Chinmay-KB** [comment]
What content should I add

**Comment by Sembauke** [comment]
> What content should I add

`freeCodeCamp is a donor-supported tax-exempt 501(c)(3) nonprofit organization (United States Federal Tax Identification Number: 82-0779546)`

We should add this on the bottom of the drawer with small letters.

**Comment by Michelphoenix98** [comment]
Is this still open?
