### ISSUE TITLE
update app modal undismissable

### ISSUE THREAD

**Issue by ShaunSHamilton** [freeCodeCamp/mobile#1267]
When there is an update of the app, a modal pops up asking if _I_ would like to do so now. However, when I do not want to, the modal is non-dismissable - no close button, and tapping outside the border of the modal does not close it either.

<details>
  <summary>Modal Image</summary>

![WhatsApp Image 2024-05-19 at 12 57 37_f753f2e0](https://github.com/freeCodeCamp/mobile/assets/51722130/0e062998-50d6-472d-8b1e-db5ec98e5eca)

</details>

<details>
  <summary>Device Info</summary>

- iOS Version: 17.4.1
- Model: iPhone SE MMXF3B/A
- App version in image

</details>

**Comment by Nirajn2311** [comment]
Yes, this is the intended behavior but in the recent version we made the requirement to show the upgrade dialog a bit relaxed and dependent on a minimum app version value which we set. This way the dialog isn't shown up everytime there's an upgrade and instead will only show up when there's a breaking change or major fixes involved in the update(as you can see in the release notes there was a breaking behavior of the MCQ challenges)

**Comment by ShaunSHamilton** [comment]
That does make a lot of sense.

The only issue was I could not update the app, because I was on mobile data, but wanted to listen to a downloaded podcast.

Thank you for the clarification, though.
