### ISSUE TITLE
Radio buttons are not getting checked for each completed excercises.

### ISSUE THREAD

**Issue by NagendraDevara** [freeCodeCamp/mobile#139]
The Android application not showing completed radio button.

![IMG_20211226_101507.jpg](https://user-images.githubusercontent.com/24850111/147399125-06d1ea1e-0bfa-461e-a9b0-fe355279c140.jpg)

As shown in the image the radio buttons are not checked even though I completed those exercises.
From desktop version everything is fine.

Android app version - 2.0.4

**Comment by Sembauke** [comment]
Hey @NagendraDevara,

Are you logged in, you need to log in to save your progress.

**Comment by NagendraDevara** [comment]
Yes I have logged in to the Android App.

**Comment by Sembauke** [comment]
Hey @ojeytonwilliams,

Could this have something to do with the code storage?

**Comment by ojeytonwilliams** [comment]
Hi @Sembauke.  Nope, the code storage only affects the editor.

Since the client is showing 113/113 challenges completed, it seems this is a display issue.

**Comment by ojeytonwilliams** [comment]
To help us debug this, @NagendraDevara, could you check if this problem appears if you go to https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/ using your mobile's browser instead of the app?  If you do, it would help if you let us know the browser, version etc. so we can try to reproduce this.

**Comment by NagendraDevara** [comment]
![IMG_20220104_171301.jpg](https://user-images.githubusercontent.com/24850111/148054156-e02abd58-b9bf-404b-8e59-8787c09dc1ad.jpg)
I have opened the link in chrome ,it is showing as above.

![Screenshot_2022-01-04-17-14-50-721_com.android.chrome.jpg](https://user-images.githubusercontent.com/24850111/148054322-23192aa5-5250-4cef-bc93-cb880f0d162b.jpg)

Please find the version details.

**Comment by ojeytonwilliams** [comment]
Thanks @NagendraDevara! That really helps narrow down where we have to look.
