### ISSUE TITLE
App Logo Discussion Issue

### ISSUE THREAD

**Issue by nhcarrigan** [freeCodeCamp/mobile#15]
This issue serves as a discussion thread for the app logo. While discussing the app in our chat, it was brought up that the logo looks a bit squished. 

One idea was to add some additional negative space around the logo, but I would love to hear what you all think as well.

**How the app appears in my play store**
![image](https://user-images.githubusercontent.com/63889819/122951162-eee86d00-d331-11eb-90b7-f27dd2932601.png)

**Forum PWA on left, our mobile app on right**
![image](https://user-images.githubusercontent.com/63889819/122952026-9796cc80-d332-11eb-9233-d55a302b7861.png)

**Comment by Nirajn2311** [comment]
There is a fixed size for the app icons in different platforms right. So I think it would be better if padding was done and from that base icon we made the icons for other platforms.

**Comment by ahmadabdolsaheb** [comment]
So the puck social ones have extra padding for situations like this: https://github.com/freeCodeCamp/design-style-guide/tree/master/assets
