### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [freeCodeCamp/mobile#199]
Currently the app available on [izzy-repo](https://apt.izzysoft.de/fdroid/index/apk/org.freecodecamp).

Would you consider putting this app on F-Droid, please?
Thankyou🙏🏿

**Comment by Sembauke** [comment]
Hey @shuvashish76, 

Can you tell some more about F-Droid.

**Comment by shuvashish76** [comment]
https://f-droid.org/en/about/

F-Droid is a non-profit alternative app store for FOSS apps, where applications in the repository are built from source.

@IzzySoft knows better as he is one of the maintainer there. _(who also runs his own [repo](https://apt.izzysoft.de/fdroid/))_

**Comment by IzzySoft** [comment]
Instead of trying to fit it all into a single comment here, may I direct you to my article series on F-Droid? From there, you can also follow the [`fdroid`](https://android.izzysoft.de/articles/tagged/fdroid) tag if you want to dig deeper. The series starts with the introductory article

[F-Droid: The privacy-friendly alternative to Google Play Store](https://android.izzysoft.de/articles/named/fdroid-intro-1)

Follow-up parts are linked from there, more articles on F-Droid topics via the mentioned tag.

**Comment by Sembauke** [comment]
Hi @IzzySoft,

I will contact the owner of the mobile app on Monday, and see what he thing about it. 
It looks pretty great though. It goes well with our intentions.

Have a nice day and happy coding 😄

**Comment by Sembauke** [comment]
Hi @IzzySoft,

Just a question, how many users make use of F-Droid? 
If that is a too private of a question please e-mail sem@freecodecamp.org.

Sorry for the late response.

**Comment by IzzySoft** [comment]
@Sembauke that's hard to tell as we don't keep statistics on that level. For some numbers-per-day, you can find the corresponding metrics here: https://fdroid.gitlab.io/metrics/search.f-droid.org/2021-01-18.json (taken from https://f-droid.org/docs/All_our_APIs/ – just replace the date as needed).

**Comment by Sembauke** [comment]
Hey @IzzySoft,

Do you guys have a terms of service/privacy policy we can look into?

Thanks.

**Comment by IzzySoft** [comment]
> These are my principles. If you don’t like them I have others.

(attributed to Groucho Marx)

A good starting point are [our docs](https://f-droid.org/docs/). There you can e.g. find our [Code of Conduct](https://f-droid.org/en/docs/Code_of_Conduct), our [Inclusion Policy](https://f-droid.org/en/docs/Inclusion_Policy). More information can also be found in [our wiki](https://gitlab.com/fdroid/wiki/-/wikis/pages). Some of those things are also spread across [articles](https://f-droid.org/en/news/)… I'm not sure if there's a document titled "service/privacy policy" somewhere, but you could bring up that question e.g. in the forum.

**Comment by Sembauke** [comment]
Hi @shuvashish76 and @IzzySoft,

Thank you for sharing F-droid, We may consider joining you in the future.

Thanks for your understanding,

Have a nice day and happy coding!

**Comment by IzzySoft** [comment]
Looking forward to that then. All the best for your project!

**Comment by yashpalgoyal1304** [comment]
@Sembauke i'll be eagerly waiting for your app to be on fdroid
(i dont use google play *hit)

**Comment by Sembauke** [comment]
Hey @licaon-kter.
any reason behind the ping?

**Comment by licaon-kter** [comment]
You can see the link?

**Comment by Sembauke** [comment]
> You can't see the link?

Yes but I do not understand what I am looking at.

**Comment by licaon-kter** [comment]
The F-Droid test build of the app (and the recipe), for you or anyone to test for correctness.

**Comment by Sembauke** [comment]
Hey @licaon-kter 
We decided not to join F-droid:
https://github.com/freeCodeCamp/mobile/issues/199#issuecomment-1052125828

**Comment by licaon-kter** [comment]
Yes yes, didn't get the _why_ though.

I thought this was riddled with non-FOSS deps, but suprise.

Anyway... yeah. Have fun...
