### ISSUE TITLE
Replace packages that do not support null safety

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#21]
The current packages do not have support for null safety and should be replaced:
- package:flutter_skeleton
- package:flutter_swiper
- package:flutter_page_indicator
- package:transformer_page_view

**Comment by Sembauke** [comment]
Potential:
https://pub.dev/packages/skeleton_loader
https://pub.dev/packages/page_indicator

**Comment by nikunjdk** [comment]
this can be closed. all such packages were being used by code related to flash cards and I have commented and punt that code it a temp folder and have removed such packages in or #39
