### ISSUE TITLE
[testing] add integration tests

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/mobile#329]
As the app gets bigger with more features, we would need more integration tests to make sure nothing is broken during deployment. Currently we have only one integration test in the news component which checks if a news article is bookmarked and visible in the bookmarks view. Both the news component and podcasts component need more integration tests.

**Comment by SmartAree** [comment]
Can I work on this?

**Comment by Sembauke** [comment]
Hi @SmartAree,
Yes for sure! Let us know if you need any help.

**Comment by VishalVR-21** [comment]
Could u please assign it to me

**Comment by Sembauke** [comment]
Hey @VishalVR-21,
We do not assign issues, feel free to work on it though.
No one seems to work on it at the moment.

Have a nice day and happy coding.
