### ISSUE TITLE
[news] personalized tutorial feed

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#332]
To make user enjoy the news-component more:

We will need an option for a personalized feed. The user should be able to subscribe to a certain author or subject they like. These authors or subjects will show up in their personalized feed. 

It would also be nice to add recommendations of certain subjects that they can subscribe to in the personalized feed and the home feed.

**Comment by QuincyLarson** [comment]
Yes – this would be really helpful in general (not just for the mobile app, but for /news in general). Sort of a way to follow specific topics like Medium.com has. This said, we don't want to have elaborate onboarding. Probably just a "follow this topic" button that, when pressed, prioritizes articles with that topic over other articles. 

For example, if someone clicked that for the Python topic, they would see the recent Python-related tutorials at the top, above other recent articles. So this would be a hybrid recommended + reverse chronological newsfeed.

**Comment by Sembauke** [comment]
Thank you Quincy.

**Comment by obumnwabude** [comment]
@QuincyLarson that means this has to be integrated first in the main /news itself before bringing it into the app right? 

Because we might now need another screen that will show you what you follow and permit you to unfollow
