### ISSUE TITLE
[suggestion] Match fonts to the FCC website theme

### ISSUE THREAD

**Issue by psk907** [freeCodeCamp/mobile#364]
The mobile app seems to use a single font-family i.e **Roboto** and the default font styles that come with Flutter. This creates some gap from the content on the [FreeCodeCamp website](https://www.freecodecamp.org/)

In order to keep things consistent between the web and mobile, I suggest using the same fonts as the website within the mobile app.
The font used in the website is **Lato** [fonts.google.com/specimen/Lato#standard-styles](https://fonts.google.com/specimen/Lato#standard-styles)

> Lato is a sans serif typeface family started in the summer of 2010 by Warsaw-based designer Łukasz Dziedzic (“Lato” means “Summer” in Polish). In December 2010 the Lato family was published under the Open Font License by his foundry tyPoland, with support from Google.

I believe that using this typeface would result in a more uniform and legible user experience.

I am ready to work on this issue and bring the new typeface to the app. However, I'd like to know your thoughts on this suggestion before proceeding.

**Comment by Nirajn2311** [comment]
Hi, that's a great suggestion and you can start working on this. Also the website uses 4 fonts which can be found here - https://design-style-guide.freecodecamp.org/#typography
