### ISSUE TITLE
Improve the UI of the progress bar in podcast episode view

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/mobile#451]
Currently the progress bar works but during the initial few seconds the ball doesn't move from the left end. This may confuse users as to whether the progress bar is working or not.

Here's a [link](https://github.com/freeCodeCamp/mobile/compare/653ad88e54d45c574615d0906584b947179ec012..c6661040f268607b67ea5898a941d72675877a2a) with an attempt to fix it but since no progress was being made we reverted back.

**Comment by Dexters-Hub** [comment]
@Nirajn2311 @Sembauke Can I work on this issue?

**Comment by Sembauke** [comment]
@Dexters-Hub Please do!

**Comment by Dexters-Hub** [comment]
> @Dexters-Hub Please do!

I have fixed the issue, do check it out
