### ISSUE TITLE
Give more information about the .env file.

### ISSUE THREAD

**Issue by bricekk** [freeCodeCamp/mobile#484]
***Give more information about the .env file.***

I think it would be good to add in the "Getting Started" section of the README.md more information about the .env file. If we explain to people how to install and work on a flutter project, it would be normal to explain to them what is the environment in which this project works (databases, auth, etc.)

**Comment by Nirajn2311** [comment]
Hi, could you look at this document - https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-mobile-app-locally . We'll be moving the documentation there.

**Comment by bricekk** [comment]
@Nirajn2311 this one is looking good. thank you

**Comment by Nirajn2311** [comment]
Thanks. I'll be closing the issue now.
