### ISSUE TITLE
[learn] the preview is visible on JavaScript challenges

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#567]
The preview is visible on JavaScript challenges, this should not be the case.

It should focus on the console. If the user taps on the "preview" tab it should say that it is not available for this challenge type.

**Comment by Spyy004** [comment]
I would love to fix this but where is the exact bug. I am searching in the app that i downloaded from play store
 but i am unable to find the preview button

**Comment by Sembauke** [comment]
Hey @Spyy004,

Thank you for showing interest in this issue. To get access to the other super-blocks, e.g. the JavaScript Algorithm and Data Structures certification, you will need to do the following:

If you have followed the documentation you should already have the following setup:

1. You have copied the sample.env in the mobile-app directory, and called the file .env.
2. You have ran `flutter pub get` to install all the different packages that we use.

After this, you can set `SHOWALLSB` to `true` and run the app with `flutter run build --debug` .

But it seems like you already have accomplished most of this. Happy coding.

**Comment by Spyy004** [comment]
No, I did not setup the codebase yet, I was just trying to see if this bug existed on the play store version app. Now that you have mentioned it, I will setup the project and find this there. Thanks for the help

**Comment by Spyy004** [comment]
Someone please assign me this bug as I have started working on it
