### ISSUE TITLE
Keyboard Won't Popup

### ISSUE THREAD

**Issue by DeMoN100** [freeCodeCamp/mobile#581]
**Describe the bug**
When I click on the text box my keyboard does not pop-up

**To Reproduce**
Tap on sign up.
Tap on type box to enter email above send code to email.

**Expected behavior**
Your keyboard should popup so you may type.

**Screenshots**
![Screen_Recording_20220917_094855](https://user-images.githubusercontent.com/8564572/190860562-49adc0f1-d55f-4d68-85e8-f6c0c71729b4.gif)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A53 5G SM-A536U
 - OS: Android 12 One UI 4.1
 - App 1.1.0

**Comment by Sembauke** [comment]
Hey @DeMoN100,

This version of the app was released about a year ago. At the moment we do not support learn in the app. We are working on it though! The best thing you can do is Sign in through GitHub or Google.

Have a nice day and happy coding.

**Comment by DeMoN100** [comment]
Thank you for the information. I highly recommend the app be updated on f-droid because this version was listed as the latest version on the f-droid repo.

**Comment by DeMoN100** [comment]
> Hey @DeMoN100, Can you link me to the page which holds this version of the app?
> 
> We do not have control over this.
> 
> Thanks

Yes sorry for the late reply. The app comes up in f-droid from this repo.

https://apt.izzysoft.de/fdroid/index/apk/org.freecodecamp
