### ISSUE TITLE
Fix the Google PlayStore description

### ISSUE THREAD

**Issue by udayan-banik** [freeCodeCamp/mobile#595]
![Screenshot_2022-09-27-01-59-12-703_com android vending](https://user-images.githubusercontent.com/47602524/192374377-33564412-9a76-4268-9f58-1a2a8fb226aa.jpg)
**Describe the bug**
Fix the description on the Play Store where it should be podcasts instead of "podcast s"
 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sembauke** [comment]
Thank you!
