### ISSUE TITLE
While watching a video on a mobile device, a huge green box covers the whole window.

### ISSUE THREAD

**Issue by nikunjdk** [freeCodeCamp/mobile#6]
![Screenshot_20210317_105816_org freecodecamp](https://user-images.githubusercontent.com/40420430/112208167-100bc580-8c3e-11eb-955e-05c057b34fea.jpg)
The green banner covers a large portion of the video while it plays making it difficult for the users to understand the video properly.

**Comment by gkathir15** [comment]
@nikunjdk  could you share the link to the page so I could recreate it, the course I visit shows youtube videos,
The green box issue can be fixed by hiding the web widget by ID from Dom.

**Comment by nikunjdk** [comment]
When you start any exercise there is an option of help. in the help option, one of the options is to watch a video. The green box appears when you start playing the video.

**Comment by raisedadead** [comment]
We starting off with a clean slate and will rethinking this mobile app ground up. I am going to close this issue in favor of the direction we are taking, where the app is not just a web view but a feature rich tool at your disposal.
