### ISSUE TITLE
Accessibility tips for the first/next release

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#65]
- [ ] - Active interactions. Ensure that all active interactions do something. Any button that can be pushed should do something when pushed. For example, if you have a no-op callback for an onPressed event, change it to show a SnackBar on the screen explaining which control you just pushed.

- [ ] - Screen reader testing. The screen reader should be able to describe all controls on the page when you tap on them, and the descriptions should be intelligible. Test your app with TalkBack (Android) and VoiceOver (iOS).

- [ ] - Contrast ratios. We encourage you to have a contrast ratio of at least 4.5:1 between controls or text and the background, 

- [ ] -  with the exception of disabled components. Images should also be vetted for sufficient contrast.

- [ ] - Context switching. Nothing should change the user’s context automatically while typing in information. Generally, the widgets should avoid changing the user’s context without some sort of confirmation action.

- [ ] - Tappable targets. All tappable targets should be at least 48x48 pixels.

- [ ] - Errors. Important actions should be able to be undone. In fields that show errors, suggest a correction if possible.

- [ ] - Color vision deficiency testing. Controls should be usable and legible in colorblind and grayscale modes.

- [ ] - Scale factors. The UI should remain legible and usable at very large scale factors for text size and display scaling.

**Comment by Sembauke** [comment]
https://flutter.dev/docs/development/accessibility-and-localization/accessibility

**Comment by Nirajn2311** [comment]
Screen reader part would take some time to implement/test so we could push that to next release. In the remaining ones, it would be better if we checked them(can be done on a meet) after we're ready with each component that has been planned for first release

**Comment by Sembauke** [comment]
going to close this for now, we can come back to it later.
