### ISSUE TITLE
[news] Change Article class/file names to tutorials

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#671]
We have recently changed the name of Articles to Tutorials. 
This should also be reflected in the class and file names.

**Comment by amitamrutiya2210** [comment]
Hello I genuinely want to work on this issues. Can i work?

**Comment by Sembauke** [comment]
@amitamrutiya2210 Yes for sure, let us know if you need any help!

**Comment by amitamrutiya2210** [comment]
means i have to replace articles word to turorials everywhere in project

**Comment by Sembauke** [comment]
That's correct, do not forget the file names also :)
