### ISSUE TITLE
[learn] the pass pane should have a share button which implements the ability to make Twitter cards

### ISSUE THREAD

**Issue by Sembauke** [freeCodeCamp/mobile#688]

**Comment by NamanAg0502** [comment]
## Feature Implementation and Contribution Interest

Hello,

I've begun working on the feature implementation, making some progress. During testing, I encountered a minor emulator issue with the Twitter website integration. You can see the current state in this [video demo](https://drive.google.com/drive/folders/1OboVvwES1J3R3wN_WxKX_p7jGm5qMMdM?usp=sharing).

I'm eager to continue contributing to the project. Could I be assigned to this issue? I'd like to complete the implementation and resolve the Twitter website issue.

Thank you!

Best regards,  
Naman

**Comment by Sembauke** [comment]
Hey @NamanAg0502,

Thank you for willing to work on this. I think I see the issue. You possibly have to login into Twitter before you can share your completion of a project. Does the user need to do this every time?

Let me know.

Do you want to open a pull-request so that we can look at it together?

**Comment by NamanAg0502** [comment]
Hey @Sembauke,

I have created a pull request, [Pull request](https://github.com/freeCodeCamp/mobile/pull/1091#issue-1855106643).

I'm implementing Twitter Cards on Android, and I'd like to know the format they should be in.

> "Flutter IOS Cli" check got failed, I think because I haven't implement for IOS platform. Will move on with IOS once android is completed.
