### ISSUE TITLE
APKs missing from releases

### ISSUE THREAD

**Issue by IzzySoft** [freeCodeCamp/mobile#734]
There are no more APKs attached to the releases (probably forgotten or the corresponding workflow broken). Could you please ensure they are attached again, starting with the latest release? Thanks!

**Comment by IzzySoft** [comment]
That was quite verbose. As I still see no APKs attached I take it means you won't provide them here?

**Comment by Nirajn2311** [comment]
Hi, the APKs have been uploaded in v3.0.1 release.

**Comment by IzzySoft** [comment]
@Nirajn2311 any chance? I mean, I'd of course accept a "no" if it's too much fuzz for you, but would be happy for a "yes" :wink:

**Comment by Nirajn2311** [comment]
Sorry for delay. I'm still working out on how to extract the signed split apks so that there won't be any issue when the user installs them.

**Comment by IzzySoft** [comment]
Thanks! Then I'll wait patiently. Just wanted to know "if", no pressure intended :smile: Looking forward to your "ping" then.
