### ISSUE TITLE
Unwanted gap between Code and Camp

### ISSUE THREAD

**Issue by IsometricShahil** [freeCodeCamp/mobile#807]
**Describe the bug**
There is a gap between Code and Camp in the Code Radio notification.

**To Reproduce**
1. Play Code Radio
2. Check the notification bar

**Expected behavior**
It should display "freeCodeCamp" instead of "freeCode Camp"

**Screenshots**
![Screenshot_2023-02-06-23-02-15-99](https://user-images.githubusercontent.com/53872662/217043696-2e45268a-1bcc-43ef-a75e-ce6b01da6a2b.png)

**Smartphone (please complete the following information):**
 - Device: Realme 2
 - OS: Android 9

**Comment by Wail-Mohammed** [comment]
I am working on this.
