### ISSUE TITLE
Please have a build without proprietary trackers

### ISSUE THREAD

**Issue by IzzySoft** [freeCodeCamp/mobile#891]
My updater just yelled a loud warning to me when fetching the last update:

    org.freecodecamp: needs NonFreeDep, needs NonFreeNet, needs Tracking

Taking a closer look:

```
Offending libs:
---------------
* Crashlytics (/com/crashlytics): NonFreeDep,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

6 offenders.
```

That, together with the fact APK size now goes beyond the allotted 30-MB-per-app limit would mean I'd have to remove the app from my repo. I'd revert to the previous release for now, but that's not much better: also beyond the limit already, and

```
Offending libs:
---------------
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep
* Firebase Analytics (/com/google/firebase/analytics): NonFreeDep,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet

4 offenders.
```

So I have to revert your app here to v2.2.1 in my repo for now, which at least comes without the offenders – but is still slightly above the 30 MB. I can close one eye on that – but closing both eyes would make me blind. Thus updates are disabled here for now. If you'd provide a build flavor coming without those offenders, I can see to re-enable updates again. Please let me know.

**Comment by Sembauke** [comment]
Thank you for bringing this to our attention. We understand your concerns about the non-free dependencies and tracking in our app, and we apologize for any inconvenience this may have caused.

Unfortunately, building two different versions of our app - one with the offending libraries and one without - is not a simple task. If you have experience with such an issue before let us know.

**Comment by IzzySoft** [comment]
I'm not a developer, so I cannot offer a hands-on. But as far as I've been told, setting up a build flavor is no rocket-science. Full details are [in the documentation](https://developer.android.com/build/build-variants) which might look more complex than it is. What I mostly saw in `build.gradle` files was just a little piece of that: mainly the first part (setting up build variants) and then just modifying the `implementation` statements by prefixing those only intended for one flavor with that flavor's name.

Example, flavors `gplay` and `foss`, you'd prefix the Firebase stuff declaring it as `gplayImplementation`. That way it would only be implemented when building the `gplay` flavor. All `implementation` statements without prefix would be shared across flavors. AndroidAuthority has [a nice tutorial](https://www.androidauthority.com/building-multiple-flavors-android-app-706436/) which probably helps you getting started. DigitalOcean has [a newer one](https://www.digitalocean.com/community/tutorials/android-build-types-product-flavors), and a third one [is here](https://scribe.rip/simform-engineering/basic-use-of-android-product-flavors-build-variants-315a4e11e435). Maybe start from the last, that seems easiest.

**Comment by Sembauke** [comment]
Thank you for the detailed explanation. I will put a help wanted label on it for now! 

I might look into this myself.

**Comment by IzzySoft** [comment]
Ah, comments crossed with the other PR. Thanks for looking into this, I'll keep my fingers crossed! :crossed_fingers:

Besides, you might find some hints of [my snippet here](https://gitlab.com/-/snippets/1896503) useful – especially if you're looking for an alternative approach: replacing the proprietary libraries by FOSS ones, and have them coming with privacy-friendly "presets". For example, replacing Crashlytics by [ACRA](https://github.com/ACRA/acra) configured with opt-in crash reports (on a crash, ACRA can prompt the user to send a mail while giving the opportunity to see what exactly would be sent). The other sections might give you nice ideas as well: the snippet is generally on how to help you getting your app "fully F/LOSS" and thus ready for inclusion with F-Droid.org :wink:

**Comment by Nirajn2311** [comment]
We have decided to continue with Firebase and to not keep flavored builds to reduce maintenance costs for us. 

Firebase is a highly maintained library compared to the other tools present with respect to Flutter and so it'll be easier and faster for us to resolve any issues we have with their products. Currently our integration tests are not completely reliable enough to ship two flavors of the app blindly. So we still do in-depth manual QA for every update and to have two packages(Firebase and a privacy-friendly equivalent) which do the same functionality would mean more maintenance costs for us. To completely replace Firebase with an alternative is something we don't plan to do as of now.

**Comment by IzzySoft** [comment]
Sad news. That means your app won't be able to enter F-Droid.org at all. :cry: As for my repo: what about the other offenders? Will they be removed, so I can re-enable updates in my repo – or not and I'll have to remove your app there, too?

**Comment by Nirajn2311** [comment]
The offenders I see from the issue description are all Firebase related and we won't be removing Firebase or releasing 2 flavors(with and without Firebase). So I guess you'll have to remove our app from your repo.

**Comment by IzzySoft** [comment]
Sad, but will do that then. With the next sync around 6 pm UTC, freeCodeCamp will be gone from my repo – and thus no longer be easily available outside Google's walled gardens. Should you one day re-decide, give me a ping and I see if I can re-establish it then.

All the best for your project meanwhile. I still have not given up hope one day you might be able to ship a "real F/LOSS" flavor. I understand it involves some hard work, and you cannot fight at all places simultaneously. But while implementing parts with proprietary libraries now, maybe it's possible to keep in mind to one day offer the free-and-open ones, so leave a door open to replace (e.g. via a flavor) in the future and don't weave it in "too deeply" :wink:
