### ISSUE TITLE
[learn] "Continue Learning" button

### ISSUE THREAD

**Issue by Nirajn2311** [freeCodeCamp/mobile#966]
A "continue learning" button which on clicking will take you to the last challenge you submitted so that you don't have the find the challenge all over again when you sit down to learn.

**Comment by vikky1701** [comment]
Heyyy
Can i resolve this issue.

**Comment by Nirajn2311** [comment]
@vikky1701 Sure you can go ahead. You can follow this [guide](https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-mobile-app-locally) on getting the mobile app to run locally for development.
